/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SgdsMasthead {
        /**
          * for full width masthead, add attribute `fluid`
         */
        "fluid": boolean;
        "sgCrest": string;
    }
}
declare global {
    interface HTMLSgdsMastheadElement extends Components.SgdsMasthead, HTMLStencilElement {
    }
    var HTMLSgdsMastheadElement: {
        prototype: HTMLSgdsMastheadElement;
        new (): HTMLSgdsMastheadElement;
    };
    interface HTMLElementTagNameMap {
        "sgds-masthead": HTMLSgdsMastheadElement;
    }
}
declare namespace LocalJSX {
    interface SgdsMasthead {
        /**
          * for full width masthead, add attribute `fluid`
         */
        "fluid"?: boolean;
        "sgCrest"?: string;
    }
    interface IntrinsicElements {
        "sgds-masthead": SgdsMasthead;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sgds-masthead": LocalJSX.SgdsMasthead & JSXBase.HTMLAttributes<HTMLSgdsMastheadElement>;
        }
    }
}
